services:
  db:
    image: dejwcake/postgres18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mayday"
      POSTGRES_DB: "ers_database"
    volumes:
      - db-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - springboot-network


  web-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/ers_database"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "mayday"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      - db
    ports:
      - "8080:8080"  # Expose your Spring Boot app on port 8080
    networks:
      - springboot-network

volumes:
  db-data:  # Persistent volume for database data

networks:
  springboot-network:
    driver: bridge
