spring.application.name=Practice-Project-2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.jdbc.hibernate.ddl-auto=update
spring.jdbc.hibernate.show-sql=true
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/sunnyday
spring.datasource.username=root
spring.datasource.password=Mayday






