spring.application.name=Practice-Project-2
spring.jdbc.properties.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jdbc.hibernate.ddl-auto=none
spring.jdbc.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5433/sunnyday
spring.datasource.username=root
spring.datasource.password=Mayday




